FROM quay.io/keycloak/keycloak:23.0 as jar
ARG JAR_FILE=external-source/target/*.jar
COPY ${JAR_FILE} external.jar

FROM quay.io/keycloak/keycloak:23.0 as builder
# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
COPY --chown=keycloak:keycloak --from=jar *.jar /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:23.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://172.20.10.2:5432/keycloak
# Postgres credentials
ENV KC_DB_USERNAME=tabunganku
ENV KC_DB_PASSWORD=tabungankudb

ENV KC_HOSTNAME=172.20.10.5
ENV KC_HOSTNAME_ADMIN=localhost
ENV KC_HOSTNAME_DEBUG=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]