scheme: http
origins: ${scheme}://localhost:8080
keycloak-host: 172.20.10.5
keycloak-port: 8180
keycloak-issuer: ${scheme}://${keycloak-host}:${keycloak-port}/realms/Tabungan

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${JDBC_DB_PASSWORD}
        url: ${JDBC_DB_URL}/${TABUNGAN_DB_NAME}
        username: ${JDBC_DB_USERNAME}
    jooq:
        sql-dialect: postgres
    mvc:
        format:
            date-time: iso

server:
    error:
        include-message: always
    ssl:
        enabled: false

springdoc:
    api-docs:
        enabled: true
        path: /tabunganku-api-docs
    swagger-ui:
        enabled: true
        path: /tabunganku-documentation

management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

logging:
    level:
        org:
            springframework:
                security: DEBUG

com:
    c4-soft:
        springaddons:
            oidc:
                ops:
                    - iss: ${keycloak-issuer}
                      username-claim: preferred_username
                      authorities:
                          - path: $.realm_access.roles
                          - path: $.resource_access.*.roles
                resourceserver:
                    permit-all:
                        - "/actuator/health/readiness"
                        - "/actuator/health/liveness"
                        - "/tabunganku-api-docs/**"
                        - "/tabunganku-documentation"
                        - "/swagger-ui/**"
                        - "/v3/api-docs/**"
                    cors:
                        - path: /**
                          allowed-origin-patterns: ${TABUNGAN_FE_URL}
